language: python
python:
- '3.7'
install:
- pip3 install -r requirements.txt
script:
- python -m unittest discover
deploy:
  - provider: heroku
    api_key: 46029a1d-acde-4b4d-afd1-28e8ee086bda
      secure:
    app: nasa-api-app
