language: python
python:
- '2.7'
- '3.7'
- 3.7-dev
- 3.8-dev
install:
- pip3 install -r requirements.txt
script:
- python -m unittest discover
deploy:
  - provider: heroku
    api_key:
      secure:
    app: nasa-api-app
